development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: boxroom
  pool: 5
  username: root
  password:
  host: localhost

test: &test
  adapter:  mysql2
  host:     localhost
  database: boxroom
  pool:     5
  username: root
  password:

cucumber:
  <<: *test