production:
  solr:
    hostname: localhost
    port: 8988
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8989
    log_level: DEBUG
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8990
    log_level: WARNING
    path: /solr/test
    